### PR TITLE
fix: use serializeAsJSON

### LINKED ISSUE #2: Use stable serialization logics
Blocked by https://github.com/excalidraw/excalidraw/issues/3532

### PR DESCRIPTION
**Pull request by azu**
fix #2

### CODE REVIEW

File: src/providers/excalidraw.js [hunk 1]
```diff
@@ -99,14 +108,8 @@ const writeExcalidraw = async (fileUrl, { elements, appState }) => {
...
     }
-    const serializedData = {
-        type: "excalidraw",
-        version: 2,
-        source: "file://",
-        elements: _clearElements(elements),
-        appState: _clearAppState(appState)
-    };
-    await fs.promises.writeFile(filePath, JSON.stringify(serializedData), "utf-8");
+    const serializedData = serializeAsJSON(elements, appState);
```
Comment (azu) [inline src/providers/excalidraw.js:111]: make simple
